//USER
export const LOGIN = 'LOGIN'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGOUT = 'LOGOUT'
export const REGISTER = 'REGISTER'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'

export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS'
export const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS'
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS'
export const LIKE_POST_SUCCESS = 'LIKE_POST_SUCCESS'

export const LOADING = 'LOADING'
export const ERROR = 'ERROR'


